#!/usr/bin/env bash
#
# ------------------------------------------------------------------
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 2 of the GNU General Public
#    License published by the Free Software Foundation.
#       (see http://www.gnu.org/licenses/gpl.html).
# ------------------------------------------------------------------
# 2018-03-03 15:19:01.0 +0100 / Gilles Quenot <gilles.quenot@sputnick.fr>
#
# vim:ts=4:sw=4

for i in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
	/var/lib/cups2freefax/cups2freefax.bash "$i" $USER
done
