#!/usr/bin/env bash
#
# ------------------------------------------------------------------
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 2 of the GNU General Public
#    License published by the Free Software Foundation.
#       (see http://www.gnu.org/licenses/gpl.html).
# ------------------------------------------------------------------
#
# 2018-03-09 02:16:46.0 +0100 / Gilles Quenot <gilles.quenot@sputnick.fr>
#
# Script d'installation de cups2freefax (wrapper)
#
# vim:ts=4:sw=4

# TODO test recuperation des parametres. bash -s ?

if systemctl --version &>/dev/null; then
    systemctl --user show-environment |
        grep 'DISPLAY\|XAUTHORITY\|DBUS_SESSION_BUS_ADDRESS' |
        sed 's/^/export /' > /tmp/cups2freefax.source
elif [[ $DISPLAY && $XAUTHORITY ]]; then
    cat<<EOF > /tmp/cups2freefax.source
export DISPLAY=${DISPLAY}
export XAUTHORITY=${XAUTHORITY}
EOF
else
    echo >&2 "DISPLAY et XAUTHORITY doivent etre correctement declares dans l'environnement"
    exit 1
fi

if sudo -v &>/dev/null; then
    sudo -s<<EOF
    /bin/bash $PWD/install_as_root "$@"
EOF
else
    su - root -c "/bin/bash $PWD/install_as_root $@"
fi
